// Package tapbump is a test-only package (no non-test .go file — see
// docs/plan/tasks/E0-L5.md's boundary note) that drives scripts/tap-bump.sh
// against a local bare git repository standing in for kazi-org/homebrew-tap,
// never a real one.
package tapbump

import (
	"bytes"
	"crypto/sha256"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"testing"
)

// moduleRoot is the directory holding go.mod, found from this file's own
// path rather than from the working directory.
func moduleRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller could not locate this test file")
	}
	root := filepath.Dir(filepath.Dir(filepath.Dir(file))) // internal/tapbump -> internal -> root
	if _, err := os.Stat(filepath.Join(root, "go.mod")); err != nil {
		t.Fatalf("no go.mod at the computed module root %s: %v", root, err)
	}
	return root
}

func gitTool(t *testing.T) string {
	t.Helper()
	path, err := exec.LookPath("git")
	if err != nil {
		t.Skipf("no git on PATH: %v", err)
	}
	return path
}

func goTool(t *testing.T) string {
	t.Helper()
	path, err := exec.LookPath("go")
	if err != nil {
		t.Skipf("no go toolchain on PATH: %v", err)
	}
	return path
}

func run(t *testing.T, dir string, name string, args ...string) string {
	t.Helper()
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	cmd.Env = sanitizedGitEnv()
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("%s %s (in %s): %v\n%s", name, strings.Join(args, " "), dir, err, out)
	}
	return string(out)
}

// sanitizedGitEnv is os.Environ() with every GIT_* variable stripped.
//
// This test invokes git against throwaway fixtures (a bare repo and its
// clones under t.TempDir()), always by an explicit cmd.Dir — but `git
// commit` exports GIT_DIR (and friends) into hooks/pre-commit's own process
// tree while a commit is in flight, and that inherits straight through `go
// test` into every exec.Command this file runs. GIT_DIR overrides cmd.Dir
// outright, so a fixture "commit" silently lands in THIS repository's real
// index instead of the fixture's. Observed directly: running this suite
// under `git commit` (hooks/pre-commit's `go test ./...`) staged this
// package's own seeded Formula/kazi.rb fixture into dira's own working
// tree, and the fixture's own commit then failed because git was pointed at
// the wrong git-dir/work-tree pair. Every git invocation in this file must
// run with a clean environment, not just an explicit cmd.Dir.
func sanitizedGitEnv() []string {
	env := os.Environ()
	out := env[:0:0]
	for _, e := range env {
		if strings.HasPrefix(e, "GIT_") {
			continue
		}
		out = append(out, e)
	}
	return out
}

const seededKaziFormula = `# Generated by the kazi release pipeline (ADR-0017). Do not hand-edit.
class Kazi < Formula
  desc "Reconciliation controller"
  homepage "https://github.com/kazi-org/kazi"
  version "1.275.1"
  license "Apache-2.0"
end
`

// newFixtureTap creates a local bare git repository seeded with an arbitrary
// Formula/kazi.rb, standing in for kazi-org/homebrew-tap — this test suite
// never touches a real one. Returns the bare repo's path (usable as a git
// remote via a plain filesystem path) and the seeded kazi.rb bytes.
func newFixtureTap(t *testing.T) (bareRepo string, kaziBytes []byte) {
	t.Helper()
	git := gitTool(t)
	dir := t.TempDir()
	bareRepo = filepath.Join(dir, "homebrew-tap.git")
	run(t, dir, git, "init", "--quiet", "--bare", "-b", "main", bareRepo)

	seed := filepath.Join(dir, "seed")
	run(t, dir, git, "clone", "--quiet", bareRepo, seed)
	if err := os.MkdirAll(filepath.Join(seed, "Formula"), 0o755); err != nil {
		t.Fatal(err)
	}
	kaziBytes = []byte(seededKaziFormula)
	if err := os.WriteFile(filepath.Join(seed, "Formula", "kazi.rb"), kaziBytes, 0o644); err != nil {
		t.Fatal(err)
	}
	run(t, seed, git, "add", "Formula/kazi.rb")
	run(t, seed, git, "-c", "user.name=fixture", "-c", "user.email=fixture@example.com",
		"commit", "--quiet", "-m", "seed: Formula/kazi.rb")
	run(t, seed, git, "push", "--quiet", "origin", "HEAD:refs/heads/main")
	return bareRepo, kaziBytes
}

// fixtureInputs is the version and per-target url/sha256 pair every test in
// this file publishes with, unless it says otherwise.
type fixtureInputs struct {
	version                           string
	darwinArm64URL, darwinArm64SHA256 string
	darwinAmd64URL, darwinAmd64SHA256 string
	linuxURL, linuxSHA256             string
}

func defaultFixtureInputs() fixtureInputs {
	return fixtureInputs{
		version:           "1.2.3",
		darwinArm64URL:    "https://github.com/kazi-org/dira/releases/download/v1.2.3/dira_darwin_arm64.tar.gz",
		darwinArm64SHA256: "1111111111111111111111111111111111111111111111111111111111111111",
		darwinAmd64URL:    "https://github.com/kazi-org/dira/releases/download/v1.2.3/dira_darwin_amd64.tar.gz",
		darwinAmd64SHA256: "3333333333333333333333333333333333333333333333333333333333333333",
		linuxURL:          "https://github.com/kazi-org/dira/releases/download/v1.2.3/dira_linux_amd64.tar.gz",
		linuxSHA256:       "2222222222222222222222222222222222222222222222222222222222222222",
	}
}

func (in fixtureInputs) args(remote string) []string {
	return []string{
		"--version", in.version,
		"--darwin-arm64-url", in.darwinArm64URL, "--darwin-arm64-sha256", in.darwinArm64SHA256,
		"--darwin-amd64-url", in.darwinAmd64URL, "--darwin-amd64-sha256", in.darwinAmd64SHA256,
		"--linux-amd64-url", in.linuxURL, "--linux-amd64-sha256", in.linuxSHA256,
		"--remote", remote,
	}
}

// generatorOutput renders the formula bytes T2's script is expected to have
// published, using T1's own generator, so this test compares against the
// real generator rather than a second copy of its template.
func generatorOutput(t *testing.T, in fixtureInputs) []byte {
	t.Helper()
	cmd := exec.Command(goTool(t), "run", "./internal/tapformula/gen",
		"--version", in.version,
		"--darwin-arm64-url", in.darwinArm64URL, "--darwin-arm64-sha256", in.darwinArm64SHA256,
		"--darwin-amd64-url", in.darwinAmd64URL, "--darwin-amd64-sha256", in.darwinAmd64SHA256,
		"--linux-amd64-url", in.linuxURL, "--linux-amd64-sha256", in.linuxSHA256,
	)
	cmd.Dir = moduleRoot(t)
	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("running the tapformula generator directly: %v", err)
	}
	return out
}

func runTapBump(t *testing.T, scriptPath string, tokenSet bool, args ...string) (stdout string, exitCode int) {
	t.Helper()
	return runTapBumpWithRoot(t, scriptPath, "", tokenSet, args...)
}

// runTapBumpWithRoot is runTapBump with an explicit DIRA_MODULE_ROOT
// override — needed only when scriptPath is a copy living outside
// scripts/, whose BASH_SOURCE-relative resolution would otherwise miss the
// real module (see DIRA_MODULE_ROOT's own comment in tap-bump.sh).
func runTapBumpWithRoot(t *testing.T, scriptPath, moduleRootOverride string, tokenSet bool, args ...string) (stdout string, exitCode int) {
	t.Helper()
	cmd := exec.Command(scriptPath, args...)
	// scripts/tap-bump.sh runs git internally (clone/add/commit/push) — the
	// same GIT_DIR leak sanitizedGitEnv's comment describes applies here
	// too, since this process is just as much a child of hooks/pre-commit's
	// `go test ./...` as run()'s direct git invocations are.
	env := sanitizedGitEnv()
	if tokenSet {
		env = append(env, "HOMEBREW_TAP_TOKEN=fixture-token-not-a-real-secret")
	} else {
		env = filterOutEnv(env, "HOMEBREW_TAP_TOKEN")
	}
	if moduleRootOverride != "" {
		env = append(env, "DIRA_MODULE_ROOT="+moduleRootOverride)
	}
	cmd.Env = env
	var buf bytes.Buffer
	cmd.Stdout = &buf
	cmd.Stderr = &buf
	err := cmd.Run()
	if err == nil {
		return buf.String(), 0
	}
	if exitErr, ok := err.(*exec.ExitError); ok {
		return buf.String(), exitErr.ExitCode()
	}
	t.Fatalf("running %s: %v\n%s", scriptPath, err, buf.String())
	return "", -1
}

// executableLines strips full-line comments (lines whose first non-blank
// character is #) from a shell script, joining what remains with newlines.
// It does not attempt to strip trailing `# comment` fragments after real
// code, since none of this script's code lines carry one.
func executableLines(src string) string {
	var b strings.Builder
	for line := range strings.SplitSeq(src, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "#") {
			continue
		}
		b.WriteString(line)
		b.WriteString("\n")
	}
	return b.String()
}

func filterOutEnv(env []string, key string) []string {
	prefix := key + "="
	out := env[:0:0]
	for _, e := range env {
		if !strings.HasPrefix(e, prefix) {
			out = append(out, e)
		}
	}
	return out
}

// latestCommitTouchedPaths returns the set of paths the default branch's
// most recent commit changed, as seen from a fresh clone of remote.
func latestCommitTouchedPaths(t *testing.T, remote string) []string {
	t.Helper()
	git := gitTool(t)
	dir := t.TempDir()
	run(t, dir, git, "clone", "--quiet", remote, "check")
	checkDir := filepath.Join(dir, "check")
	out := run(t, checkDir, git, "diff-tree", "--no-commit-id", "--name-only", "-r", "HEAD")
	var paths []string
	for line := range strings.SplitSeq(strings.TrimSpace(out), "\n") {
		if line != "" {
			paths = append(paths, line)
		}
	}
	return paths
}

func fileAtHEAD(t *testing.T, remote, path string) []byte {
	t.Helper()
	git := gitTool(t)
	dir := t.TempDir()
	run(t, dir, git, "clone", "--quiet", remote, "check")
	checkDir := filepath.Join(dir, "check")
	b, err := os.ReadFile(filepath.Join(checkDir, path))
	if err != nil {
		t.Fatalf("reading %s at HEAD: %v", path, err)
	}
	return b
}

func headCommit(t *testing.T, remote string) string {
	t.Helper()
	git := gitTool(t)
	dir := t.TempDir()
	run(t, dir, git, "clone", "--quiet", remote, "check")
	return strings.TrimSpace(run(t, filepath.Join(dir, "check"), git, "rev-parse", "HEAD"))
}

// --- the real test ---

func TestPublish(t *testing.T) {
	if testing.Short() {
		t.Skip("shells out to git and go run; skipped under -short")
	}
	root := moduleRoot(t)
	scriptPath := filepath.Join(root, "scripts", "tap-bump.sh")
	if _, err := os.Stat(scriptPath); err != nil {
		t.Fatalf("scripts/tap-bump.sh not found: %v", err)
	}
	in := defaultFixtureInputs()

	t.Run("with a token: publishes Formula/dira.rb by name, leaves kazi.rb untouched", func(t *testing.T) {
		remote, kaziBefore := newFixtureTap(t)

		stdout, code := runTapBump(t, scriptPath, true, in.args(remote)...)
		if code != 0 {
			t.Fatalf("tap-bump.sh exited %d, want 0:\n%s", code, stdout)
		}

		touched := latestCommitTouchedPaths(t, remote)
		if len(touched) != 1 || touched[0] != "Formula/dira.rb" {
			t.Fatalf("latest commit touched %v, want exactly [\"Formula/dira.rb\"]", touched)
		}

		got := fileAtHEAD(t, remote, "Formula/dira.rb")
		want := generatorOutput(t, in)
		if !bytes.Equal(got, want) {
			t.Errorf("published Formula/dira.rb does not match the generator's output for the same inputs\n--- got ---\n%s\n--- want ---\n%s", got, want)
		}

		kaziAfter := fileAtHEAD(t, remote, "Formula/kazi.rb")
		if sha256.Sum256(kaziAfter) != sha256.Sum256(kaziBefore) {
			t.Error("Formula/kazi.rb's bytes changed; the publish must never touch it")
		}
	})

	t.Run("with the token unset: no clone, no commit, no push, exit 0, names HOMEBREW_TAP_TOKEN", func(t *testing.T) {
		remote, _ := newFixtureTap(t)
		before := headCommit(t, remote)

		stdout, code := runTapBump(t, scriptPath, false, in.args(remote)...)
		if code != 0 {
			t.Fatalf("tap-bump.sh with no token exited %d, want 0:\n%s", code, stdout)
		}
		if !strings.Contains(stdout, "HOMEBREW_TAP_TOKEN") {
			t.Errorf("tap-bump.sh output does not name HOMEBREW_TAP_TOKEN:\n%s", stdout)
		}

		after := headCommit(t, remote)
		if after != before {
			t.Errorf("remote's HEAD moved from %s to %s with no token set; nothing should have been pushed", before, after)
		}
	})

	t.Run("a second publish of identical inputs is a no-op", func(t *testing.T) {
		remote, _ := newFixtureTap(t)

		_, code := runTapBump(t, scriptPath, true, in.args(remote)...)
		if code != 0 {
			t.Fatalf("first publish exited %d, want 0", code)
		}
		firstCommit := headCommit(t, remote)

		_, code = runTapBump(t, scriptPath, true, in.args(remote)...)
		if code != 0 {
			t.Fatalf("second publish exited %d, want 0", code)
		}
		secondCommit := headCommit(t, remote)

		if firstCommit != secondCommit {
			t.Errorf("a second publish of identical inputs produced a new commit (%s -> %s); it should be a no-op", firstCommit, secondCommit)
		}
	})

	t.Run("the script never stages with -A and never force-pushes", func(t *testing.T) {
		raw, err := os.ReadFile(scriptPath)
		if err != nil {
			t.Fatalf("reading %s: %v", scriptPath, err)
		}
		// Executable lines only — the file's own prose (this task's guard,
		// stated in its header comment) mentions "git add -A" and "force"
		// by name, and a check that cannot tell code from a comment
		// describing the code is not evidence of anything.
		code := executableLines(string(raw))
		if regexp.MustCompile(`git add[^\n]*-A`).MatchString(code) {
			t.Error("scripts/tap-bump.sh contains a `git add ... -A`; it must stage Formula/dira.rb by name only")
		}
		if regexp.MustCompile(`git push[^\n]*(--force|\s-f\b)`).MatchString(code) {
			t.Error("scripts/tap-bump.sh contains a forced git push; a force-push can overwrite concurrent tap changes")
		}
	})

	t.Run("both sides: a git-add--A variant touching the whole Formula/ directory changes kazi.rb's bytes", func(t *testing.T) {
		remote, kaziBefore := newFixtureTap(t)
		brokenPath := brokenAddAllScript(t, scriptPath)

		stdout, code := runTapBumpWithRoot(t, brokenPath, root, true, in.args(remote)...)
		if code != 0 {
			t.Fatalf("broken script exited %d, want 0:\n%s", code, stdout)
		}

		kaziAfter := fileAtHEAD(t, remote, "Formula/kazi.rb")
		if bytes.Equal(kaziAfter, kaziBefore) {
			t.Fatal("expected the git-add--A variant to clobber Formula/kazi.rb, but its bytes are unchanged — the guard cannot be observed catching anything")
		}
	})
}

// brokenAddAllScript writes a copy of the real tap-bump.sh with two changes,
// both representing the exact risk docs/plan/tasks/E0-L5.md's E0-L5-T2
// names: a generator step that (wrongly) touches the whole Formula/
// directory instead of Formula/dira.rb alone, staged with `git add -A`
// instead of the named path. DIRA_MODULE_ROOT is set by the caller so the
// copy — now living in a temp directory — still resolves the real module
// for `go run ./internal/tapformula/gen`.
func brokenAddAllScript(t *testing.T, realScriptPath string) string {
	t.Helper()
	raw, err := os.ReadFile(realScriptPath)
	if err != nil {
		t.Fatalf("reading %s: %v", realScriptPath, err)
	}
	src := string(raw)

	writeLine := `printf '%s\n' "$formula" > "$workdir/tap/Formula/dira.rb"`
	if !strings.Contains(src, writeLine) {
		t.Fatal("could not find the Formula/dira.rb write line to mutate")
	}
	src = strings.Replace(src, writeLine,
		writeLine+"\n"+`printf '# clobbered by a directory-wide write\n' >> "$workdir/tap/Formula/kazi.rb"`,
		1)

	addLine := "git add Formula/dira.rb"
	if !strings.Contains(src, addLine) {
		t.Fatal("could not find the named `git add` line to mutate")
	}
	src = strings.Replace(src, addLine, "git add -A", 1)

	dir := t.TempDir()
	brokenPath := filepath.Join(dir, "tap-bump-broken.sh")
	if err := os.WriteFile(brokenPath, []byte(src), 0o755); err != nil {
		t.Fatalf("writing broken script copy: %v", err)
	}
	return brokenPath
}
