// Package tapformula renders Formula/dira.rb — the Homebrew formula
// kazi-org/homebrew-tap serves alongside its existing Formula/kazi.rb.
//
// This package touches no filesystem and shells out to nothing: it takes a
// version and two targets' download coordinates and returns bytes. That
// makes it exempt from dec-0005's filesystem-boundary check with no
// allowlist entry needed at all — publishing those bytes to a real tap is
// scripts/tap-bump.sh's job (internal/tapbump), not this package's.
//
// The shape mirrors Formula/kazi.rb: a class extending Formula, one
// on_macos block and one on_linux block each carrying its own url and
// sha256, an install method, and a test block. It differs from kazi's own
// formula in one deliberate way — kazi's on_macos/on_linux blocks nest
// on_arm/on_intel because kazi ships bare binaries for four platform pairs;
// dira ships exactly one architecture per OS (darwin/arm64, linux/amd64, per
// docs/plan/lanes/E0.md's own scope), so each OS block carries its url and
// sha256 directly. And the test block asserts the installed binary's
// `--version` output equals the formula's own declared version, rather than
// kazi's weaker "the string kazi appears in --help output" — a version
// mismatch is exactly what a formula pointing at a stale release looks like,
// and only the stronger assertion catches it.
package tapformula

import (
	"bytes"
	"errors"
	"text/template"
)

// Target is one platform's release asset: where to download it, and the
// sha256 Homebrew verifies it against.
type Target struct {
	URL    string
	SHA256 string
}

// Input is everything Generate needs to render Formula/dira.rb.
type Input struct {
	// Version is the formula's declared version, with no leading "v" —
	// goreleaser's {{.Version}} template variable already strips it, and
	// the generator does not strip it a second time.
	Version string

	DarwinArm64 Target
	LinuxAmd64  Target
}

// Named errors for each required field, so a caller (and this package's own
// test) can assert on which one is missing rather than on "an error
// occurred."
var (
	ErrMissingVersion      = errors.New("tapformula: version is required")
	ErrMissingDarwinURL    = errors.New("tapformula: darwin/arm64 url is required")
	ErrMissingDarwinSHA256 = errors.New("tapformula: darwin/arm64 sha256 is required")
	ErrMissingLinuxURL     = errors.New("tapformula: linux/amd64 url is required")
	ErrMissingLinuxSHA256  = errors.New("tapformula: linux/amd64 sha256 is required")
)

// formulaTemplate mirrors Formula/kazi.rb's own header and shape. "Generated
// by ... Do not hand-edit." is load-bearing prose, not decoration: it is
// what tells the next person reading kazi-org/homebrew-tap that editing this
// file directly will be overwritten by the next release.
const formulaTemplate = `# Generated by the dira release pipeline. Do not hand-edit.
class Dira < Formula
  desc "A memory of why, kept in the repo as plain files"
  homepage "https://github.com/kazi-org/dira"
  version "{{.Version}}"
  license "Apache-2.0"

  on_macos do
    url "{{.DarwinArm64.URL}}"
    sha256 "{{.DarwinArm64.SHA256}}"
  end

  on_linux do
    url "{{.LinuxAmd64.URL}}"
    sha256 "{{.LinuxAmd64.SHA256}}"
  end

  def install
    bin.install "dira"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/dira --version").strip
  end
end
`

var tmpl = template.Must(template.New("formula").Parse(formulaTemplate))

// Generate renders Formula/dira.rb's bytes for the given input.
func Generate(in Input) ([]byte, error) {
	switch {
	case in.Version == "":
		return nil, ErrMissingVersion
	case in.DarwinArm64.URL == "":
		return nil, ErrMissingDarwinURL
	case in.DarwinArm64.SHA256 == "":
		return nil, ErrMissingDarwinSHA256
	case in.LinuxAmd64.URL == "":
		return nil, ErrMissingLinuxURL
	case in.LinuxAmd64.SHA256 == "":
		return nil, ErrMissingLinuxSHA256
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, in); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
