// Package tapformula renders Formula/dira.rb — the Homebrew formula
// kazi-org/homebrew-tap serves alongside its existing Formula/kazi.rb.
//
// This package touches no filesystem and shells out to nothing: it takes a
// version and three targets' download coordinates and returns bytes. That
// makes it exempt from dec-0005's filesystem-boundary check with no
// allowlist entry needed at all — publishing those bytes to a real tap is
// scripts/tap-bump.sh's job (internal/tapbump), not this package's.
//
// The shape mirrors Formula/kazi.rb: a class extending Formula, an on_macos
// block nesting on_arm/on_intel, an on_linux block nesting on_intel, an
// install method, and a test block. v0.1.0's first real `brew install`
// failed on the founder's own Intel MacBook with "bad CPU type in
// executable": the formula this package used to generate had no arch
// conditional at all inside on_macos, so `brew install` on every Mac — arm64
// or amd64 — resolved to the single url/sha256 the block carried, which was
// built for arm64. This package now mirrors kazi's own on_arm/on_intel
// nesting for exactly that reason. dira's linux side stays intel-only on
// purpose: the DGX build (linux/arm64) is not something brew ever serves,
// so on_linux carries no on_arm block and Input carries no field for one —
// the formula names exactly the archives it pins, nothing else. The test
// block asserts the installed binary's `--version` output equals the
// formula's own declared version, rather than kazi's weaker "the string kazi
// appears in --help output" — a version mismatch is exactly what a formula
// pointing at a stale release looks like, and only the stronger assertion
// catches it.
package tapformula

import (
	"bytes"
	"errors"
	"text/template"
)

// Target is one platform's release asset: where to download it, and the
// sha256 Homebrew verifies it against.
type Target struct {
	URL    string
	SHA256 string
}

// Input is everything Generate needs to render Formula/dira.rb.
type Input struct {
	// Version is the formula's declared version, with no leading "v" —
	// goreleaser's {{.Version}} template variable already strips it, and
	// the generator does not strip it a second time.
	Version string

	DarwinArm64 Target
	DarwinAmd64 Target
	LinuxAmd64  Target
}

// Named errors for each required field, so a caller (and this package's own
// test) can assert on which one is missing rather than on "an error
// occurred."
var (
	ErrMissingVersion        = errors.New("tapformula: version is required")
	ErrMissingDarwinArm64URL = errors.New("tapformula: darwin/arm64 url is required")
	ErrMissingDarwinArm64SHA = errors.New("tapformula: darwin/arm64 sha256 is required")
	ErrMissingDarwinAmd64URL = errors.New("tapformula: darwin/amd64 url is required")
	ErrMissingDarwinAmd64SHA = errors.New("tapformula: darwin/amd64 sha256 is required")
	ErrMissingLinuxURL       = errors.New("tapformula: linux/amd64 url is required")
	ErrMissingLinuxSHA256    = errors.New("tapformula: linux/amd64 sha256 is required")
)

// formulaTemplate mirrors Formula/kazi.rb's own header and shape, including
// its on_arm/on_intel nesting inside on_macos. "Generated by ... Do not
// hand-edit." is load-bearing prose, not decoration: it is what tells the
// next person reading kazi-org/homebrew-tap that editing this file directly
// will be overwritten by the next release.
const formulaTemplate = `# Generated by the dira release pipeline. Do not hand-edit.
class Dira < Formula
  desc "A memory of why, kept in the repo as plain files"
  homepage "https://github.com/kazi-org/dira"
  version "{{.Version}}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "{{.DarwinArm64.URL}}"
      sha256 "{{.DarwinArm64.SHA256}}"
    end
    on_intel do
      url "{{.DarwinAmd64.URL}}"
      sha256 "{{.DarwinAmd64.SHA256}}"
    end
  end

  on_linux do
    on_intel do
      url "{{.LinuxAmd64.URL}}"
      sha256 "{{.LinuxAmd64.SHA256}}"
    end
  end

  def install
    bin.install "dira"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/dira --version").strip
  end
end
`

var tmpl = template.Must(template.New("formula").Parse(formulaTemplate))

// Generate renders Formula/dira.rb's bytes for the given input.
func Generate(in Input) ([]byte, error) {
	switch {
	case in.Version == "":
		return nil, ErrMissingVersion
	case in.DarwinArm64.URL == "":
		return nil, ErrMissingDarwinArm64URL
	case in.DarwinArm64.SHA256 == "":
		return nil, ErrMissingDarwinArm64SHA
	case in.DarwinAmd64.URL == "":
		return nil, ErrMissingDarwinAmd64URL
	case in.DarwinAmd64.SHA256 == "":
		return nil, ErrMissingDarwinAmd64SHA
	case in.LinuxAmd64.URL == "":
		return nil, ErrMissingLinuxURL
	case in.LinuxAmd64.SHA256 == "":
		return nil, ErrMissingLinuxSHA256
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, in); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
