package tapformula

import (
	"bytes"
	"errors"
	"os"
	"strings"
	"testing"
)

// fixtureInput is the fully-valid baseline every negative case in this file
// mutates exactly one field of. Every acceptance-line assertion below is
// checked against this same baseline so a negative case is proven against a
// positive one in the same run, not in isolation.
func fixtureInput() Input {
	return Input{
		Version: "1.2.3",
		DarwinArm64: Target{
			URL:    "https://github.com/kazi-org/dira/releases/download/v1.2.3/dira_darwin_arm64.tar.gz",
			SHA256: "1111111111111111111111111111111111111111111111111111111111111111",
		},
		DarwinAmd64: Target{
			URL:    "https://github.com/kazi-org/dira/releases/download/v1.2.3/dira_darwin_amd64.tar.gz",
			SHA256: "3333333333333333333333333333333333333333333333333333333333333333",
		},
		LinuxAmd64: Target{
			URL:    "https://github.com/kazi-org/dira/releases/download/v1.2.3/dira_linux_amd64.tar.gz",
			SHA256: "2222222222222222222222222222222222222222222222222222222222222222",
		},
	}
}

// TestGenerateFormula is this package's whole acceptance line
// (docs/plan/tasks/E0-L5.md's E0-L5-T1).
func TestGenerateFormula(t *testing.T) {
	golden, err := os.ReadFile("testdata/golden.rb")
	if err != nil {
		t.Fatalf("reading golden fixture: %v", err)
	}

	t.Run("byte-identical to the golden fixture", func(t *testing.T) {
		got, err := Generate(fixtureInput())
		if err != nil {
			t.Fatalf("Generate: %v", err)
		}
		if !bytes.Equal(got, golden) {
			t.Fatalf("Generate output does not match testdata/golden.rb\n--- got ---\n%s\n--- want ---\n%s", got, golden)
		}
	})

	t.Run("golden fixture carries the required shape", func(t *testing.T) {
		s := string(golden)
		for _, want := range []string{
			"class Dira < Formula",
			"on_macos do",
			"on_arm do",
			"on_intel do",
			"on_linux do",
			`version "1.2.3"`,
			"# Generated by",
			"Do not hand-edit.",
			"test do",
		} {
			if !strings.Contains(s, want) {
				t.Errorf("golden fixture missing %q", want)
			}
		}
		if strings.Count(s, "on_macos do") != 1 {
			t.Errorf("golden fixture must have exactly one on_macos block")
		}
		if strings.Count(s, "on_linux do") != 1 {
			t.Errorf("golden fixture must have exactly one on_linux block")
		}
		// on_macos nests one on_arm and one on_intel block; on_linux nests
		// one on_intel block (linux/arm64 — the DGX — is never served by
		// brew, so on_linux carries no on_arm block at all). Three
		// arch-conditional blocks in total.
		if strings.Count(s, "on_arm do") != 1 {
			t.Errorf("golden fixture must have exactly one on_arm block, got %d", strings.Count(s, "on_arm do"))
		}
		if strings.Count(s, "on_intel do") != 2 {
			t.Errorf("golden fixture must have exactly two on_intel blocks (one under on_macos, one under on_linux), got %d", strings.Count(s, "on_intel do"))
		}
		// Every arch-conditional block carries its own url/sha256: three of
		// each, not one shared pair per OS.
		if strings.Count(s, "url \"") != 3 {
			t.Errorf("golden fixture must declare a url in each of the three arch blocks, got %d", strings.Count(s, "url \""))
		}
		if strings.Count(s, "sha256 \"") != 3 {
			t.Errorf("golden fixture must declare a sha256 in each of the three arch blocks, got %d", strings.Count(s, "sha256 \""))
		}
		// The test block must check the installed --version output against
		// the formula's own declared version — the lane's correction to
		// kazi's weaker --help-contains-name assertion.
		if !strings.Contains(s, "--version") {
			t.Errorf("golden fixture's test block must assert on --version output, not --help")
		}
		if strings.Contains(s, "--help") {
			t.Errorf("golden fixture's test block must not fall back to kazi's weaker --help assertion")
		}
	})

	t.Run("golden-match assertion can fail", func(t *testing.T) {
		// Mutate exactly one field (the linux sha256) and confirm the diff
		// against the golden fixture lands on the expected line, proving
		// this is a real byte comparison and not a check that always
		// passes.
		in := fixtureInput()
		in.LinuxAmd64.SHA256 = "deadbeef"
		got, err := Generate(in)
		if err != nil {
			t.Fatalf("Generate: %v", err)
		}
		if bytes.Equal(got, golden) {
			t.Fatal("mutated input produced byte-identical output to the golden fixture — the comparison cannot fail")
		}
		gotLines := strings.Split(string(got), "\n")
		goldenLines := strings.Split(string(golden), "\n")
		diffLine := -1
		for i := range gotLines {
			if i >= len(goldenLines) || gotLines[i] != goldenLines[i] {
				diffLine = i
				break
			}
		}
		if diffLine == -1 {
			t.Fatal("expected a differing line, found none")
		}
		if !strings.Contains(gotLines[diffLine], "deadbeef") {
			t.Fatalf("expected the diff to land on the mutated linux sha256 line, got line %d: %q", diffLine, gotLines[diffLine])
		}
		// And the diff must land on the linux block's sha256, not the
		// darwin one — proving the mutation is attributed to the right
		// field, not merely that *some* line moved.
		if strings.Contains(gotLines[diffLine], "darwin") {
			t.Fatalf("diff landed on a darwin-related line for a linux-only mutation: %q", gotLines[diffLine])
		}
	})

	t.Run("each required per-target field is individually required", func(t *testing.T) {
		cases := []struct {
			name    string
			mutate  func(*Input)
			wantErr error
		}{
			{"darwin arm64 url empty", func(in *Input) { in.DarwinArm64.URL = "" }, ErrMissingDarwinArm64URL},
			{"darwin arm64 sha256 empty", func(in *Input) { in.DarwinArm64.SHA256 = "" }, ErrMissingDarwinArm64SHA},
			{"darwin amd64 url empty", func(in *Input) { in.DarwinAmd64.URL = "" }, ErrMissingDarwinAmd64URL},
			{"darwin amd64 sha256 empty", func(in *Input) { in.DarwinAmd64.SHA256 = "" }, ErrMissingDarwinAmd64SHA},
			{"linux url empty", func(in *Input) { in.LinuxAmd64.URL = "" }, ErrMissingLinuxURL},
			{"linux sha256 empty", func(in *Input) { in.LinuxAmd64.SHA256 = "" }, ErrMissingLinuxSHA256},
		}
		for _, tc := range cases {
			t.Run(tc.name, func(t *testing.T) {
				in := fixtureInput() // otherwise-fully-valid baseline
				tc.mutate(&in)
				got, err := Generate(in)
				if !errors.Is(err, tc.wantErr) {
					t.Fatalf("Generate() error = %v, want %v", err, tc.wantErr)
				}
				if got != nil {
					t.Fatalf("Generate() returned %d bytes of output alongside an error, want none", len(got))
				}
			})
		}
	})

	t.Run("missing version is also rejected", func(t *testing.T) {
		in := fixtureInput()
		in.Version = ""
		got, err := Generate(in)
		if !errors.Is(err, ErrMissingVersion) {
			t.Fatalf("Generate() error = %v, want %v", err, ErrMissingVersion)
		}
		if got != nil {
			t.Fatalf("Generate() returned output alongside an error")
		}
	})
}
