#!/bin/sh
# Bad fixture: proves check-drafts.mjs's deny-list scan catches a
# `gh pr create` invocation. Never run this file; it exists only as text
# for the checker to scan (see check-drafts.selftest.mjs).
gh pr create --title "ship it" --body "auto-generated by an agent"
