# Generated by the dira release pipeline. Do not hand-edit.
class Dira < Formula
  desc "A memory of why, kept in the repo as plain files"
  homepage "https://github.com/kazi-org/dira"
  version "1.2.3"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/kazi-org/dira/releases/download/v1.2.3/dira_darwin_arm64.tar.gz"
    sha256 "1111111111111111111111111111111111111111111111111111111111111111"
  end

  on_linux do
    url "https://github.com/kazi-org/dira/releases/download/v1.2.3/dira_linux_amd64.tar.gz"
    sha256 "2222222222222222222222222222222222222222222222222222222222222222"
  end

  def install
    bin.install "dira"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/dira --version").strip
  end
end
